---
site_name: Ansible Package Release Management
site_url: https://ansible.readthedocs.io/projects/ansible-build-data
repo_url: https://github.com/ansible-community/ansible-build-data
theme:
  name: ansible
  features:
    - content.code.copy
    - navigation.footer
  # NOTE(gotmax23): I dislike web fonts in general and the Red Hat fonts from
  # the Ansible theme in particular
  font: false
# REUSE-IgnoreStart
copyright: >
  Copyright (C) 2023 Ansible Project Authors |
  SPDX-License-Identifier: <a style="text-decoration: underline;" href="https://github.com/ansible-community/ansible-build-data/blob/main/LICENSE">GPL-3.0-or-later</a>
# REUSE-IgnoreEnd
markdown_extensions:
  # Builtin
  - admonition
  - toc:
      permalink: true
  # pymdownx
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
nav:
  - Ansible Build Data: README.md
  - Automated Ansible Release Process: automated-process.md
  - Manual Ansible Release Process: release-process.md
  - policies.md
  - new-ansible-and-freezes.md
