name: antsibull-build tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out antsibull
        uses: actions/checkout@v2
        with:
          repository: ansible-community/antsibull
          ref: main
          path: antsibull

      - name: Pre-create build directory
        run: mkdir -p antsibull/build

      # This is where the antsibull build-release role expects it by default
      - name: Check out ansible-build-data under antsibull build directory
        uses: actions/checkout@v2
        with:
          path: antsibull/build/ansible-build-data

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry ansible-core

      - name: Test building a release with the defaults
        working-directory: antsibull
        run: |
          ansible-playbook -vv playbooks/build-single-release.yaml -e antsibull_data_reset=false -e antsibull_ansible_version=5.0.0a3

      - name: Combine and upload coverage stats
        working-directory: antsibull
        run: |
          poetry run coverage combine .coverage.*
          poetry run coverage report
          poetry run coverage xml -i
          poetry run codecov
