---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

name: Lint repository
'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Thursday at 04:00 UTC)
  schedule:
    - cron: '0 4 * * 4'

jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out ansible-build-data
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          pip install yamllint

      - name: Lint YAML files
        run: |
          yamllint .
