name: Upload-ansible-release-artifacts-to-pypi
on:
  workflow_dispatch:
    inputs:
      ansible-version:
        description: 'Release Version. Example : 11.1.0'
        required: true
      ansible-major-version:
        description: 'Exmaple 11'
        required: true

env:
  BUILD_DATA_DIR: "antsibull/build/ansible-build-data/${{ inputs.ansible-major-version }}"
  BUILDFILE: "ansible-${{ inputs.ansible-major-version }}.build"
  DEPSFILE: "ansible-${{ inputs.ansible-version }}.deps"

jobs:
  publish:
    name: 'Upload Ansible community distribution (${{ inputs.ansible-version }}) to PyPI'
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ansible/${{ inputs.ansible-version }}
    permissions:
      id-token: write

    steps:
      - name: Check out antsibull
        uses: actions/checkout@v3
        with:
          repository: ansible-community/antsibull
          path: antsibull


      - name: Pre-create build directory
        run: |
          mkdir -p antsibull/build

# We need to checkout the docs repo here

      # This is where the antsibull build-release role expects it by default
      - name: Check out ansible-build-data under antsibull build directory
        uses: actions/checkout@v3
        with:
          path: antsibull/build/ansible-build-data

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: antsibull
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible-core antsibull
          ansible-galaxy collection install community.general


      - name: Create sdist and wheel using the deps file created in the ansible-build-data Release PR
        working-directory: antsibull
        run: |
          ansible-playbook -vv playbooks/build-single-release.yaml -e 'antsibull_ansible-version="${{ inputs.ansible-version }}"' -e antsibull_data_reset=false

      - name: Upload Ansible sdist and wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: antsibull/build

      - name: Create git tag
        working-directory: antsibull/build/ansible-build-data
        run: |
          git tag -a ${{ inputs.ansible-version }} -m "Ansible ${{ inputs.ansible-version }}: Changelog, Porting Guide and Dependent Collection Details"
          git push origin ${{ inputs.ansible-version }}


# Create the tag




